### ISSUE TITLE
Syntax coloring: `init [number] python` statement is only colored in keyword color when number is negative

### ISSUE THREAD

**Issue by hsandt** [koroshiya/Sublime-Renpy#11]
Reproduction steps:

`init -999 python:`
`init -0 python:`
=> OK, colored properly

![image](https://github.com/koroshiya/Sublime-Renpy/assets/1067772/e57ce38d-95bb-41c1-9307-761c968d8e38)

`init 0 python:`
`init 999 python:`
=> not colored at all. In addition, the block below is also incorrectly colored

![image](https://github.com/koroshiya/Sublime-Renpy/assets/1067772/393a2c35-63bd-40d3-824e-cb3aadef4ece)

**Comment by koroshiya** [comment]
Thanks @hsandt, this is now fixed in v1.2.17
Positive numbers were supported before, but required a + in front of the number. Now you can have a plus, minus, or no operator.
