### ISSUE TITLE
Multi-line strings are not yet supported.

### ISSUE THREAD

**Issue by williamd1k0** [koroshiya/Sublime-Renpy#3]
Unlike Python, the Ren'Py language supports multi-line strings.
The Sublime is recognizing only one line strings.
Using version 1.1.10

![2015-10-21 13_47_41-c__users_diko_documents_github_language-renpy_example rpy osmitadores github io](https://cloud.githubusercontent.com/assets/10428035/10642005/953468e2-77fa-11e5-86cc-7e4e0aeb3b9f.png)

**Comment by koroshiya** [comment]
Fixed in 1.1.11, both for single and double quoted lines.

**Comment by itsaferbie** [comment]
I'm using version 1.1.12 and I'm getting the errors for multi-line strings.
![multi-linestrings](https://cloud.githubusercontent.com/assets/8745512/10675314/766a3e40-78cd-11e5-91c8-6371420e9c38.png)

**Comment by williamd1k0** [comment]
Still not working for me too.

**Comment by koroshiya** [comment]
It seems the regex handling has changed between the current stable version (3083) and the current dev version (3095). I'm using the latter, and multi-line is working.
<a href="http://imgur.com/Ds7qicx"><img src="http://i.imgur.com/Ds7qicx.png" title="source: imgur.com" /></a>
I'll downgrade to 3083 and find a solution that works on both.

**Comment by koroshiya** [comment]
Uhh... Scratch that. I've downgraded to 3083, installed RenpyLanguage from Package Control, and multi-line strings are still working.

@williamd1k0 Your screenshot doesn't show highlighting for the show statement, the dollar command, or the below label. Are you sure you have RenpyLanguage set as the language for the file open there? It looks more like the syntax highlighting for Python.

@itsaferbie @williamd1k0 @Nolanlemahn What build of Sublime Text 3 are you using (Help -> About Sublime Text), and on what platform?
I've tried 3083 and 3095 on Linux, and 3083 on Windows, and have been unable to replicate this issue.

**Comment by itsaferbie** [comment]
I'm using build 3083 on Windows 7. I tried to see if it was just my machine that was not doing it, but I had the same results on my laptop as well same build just Windows 8.1.

**Comment by koroshiya** [comment]
@itsaferbie Could you take a screenshot including the label declaration (and a multi-line string a few lines after it)?
Your screenshot clearly shows that you have RenpyLanguage set and up to date, but the text is acting as though it isn't in a label block. So my guess is that RenpyLanguage isn't reading your label block correctly and thus the text isn't in the right context.
The only other explanation that comes to mind is that you have a line that isn't indented correctly (this includes comments... which is something I need to fix), so the context reverts to Python.
eg.
<a href="http://imgur.com/sKW4T8W"><img src="http://i.imgur.com/sKW4T8W.png" title="source: imgur.com" /></a>

**Comment by itsaferbie** [comment]
I believe I found the issue.

When using the default start label that Ren'py creates I get the error as shown.
![error](https://cloud.githubusercontent.com/assets/8745512/10679072/2eca8ff6-78e4-11e5-9a5d-97398144cd35.png)

But as soon as I add the wait after it, it doesn't give me this error, as shown.
![noerror](https://cloud.githubusercontent.com/assets/8745512/10679077/33eeeacc-78e4-11e5-94be-ef1138d58280.png)

**Comment by koroshiya** [comment]
Thanks @itsaferbie 
In that case, this is extremely easy to fix; just gotta make the brackets optional.
Version 1.1.13 should fix this.

**Comment by williamd1k0** [comment]
Indeed, the print was wrong, but that's because I was testing various versions then forgot to change the language in time to print. It is now resolved in version 1.1.13.
Thanks :wink:
