### ISSUE TITLE
ST Build 3.2 raises new regex error

### ISSUE THREAD

**Issue by RenpyRemix** [koroshiya/Sublime-Renpy#7]
Seem to be having an error thrown after the recent Sublime update

[x] target of repeat operator is invalid in regex \{{?={?x:
... etc

**Comment by koroshiya** [comment]
The problem seems to be that the new version of ST doesn't like the lookahead regex which matches spacing after a colon.
I think the solution will be to rewrite the regex differently, but I haven't figured out how yet. I'll keep experimenting.

**Comment by koroshiya** [comment]
After further inspection, it looks like the problems with ST 3.2 run much deeper than that, and just addressing that particular issue doesn't help much. I think the proper solution will be to replace the existing tmLanguage file with ST's newer sublime-syntax file format.

**Comment by RenpyRemix** [comment]
Regex, to me, has always been a part of programming that fails to stay retained in my head after using it. I can literally use it one week and by the following week have forgotten all I learned.
As such, I doubt I would be much help fixing this.

Nice work on the extension btw and thank you for taking the time to look at this.

**Comment by koroshiya** [comment]
Actually I was wrong. Regex is still kinda the problem, but it's more of a YAML vs XML thing.

Sublime-Renpy passes context to source.python when you create a python block. This tells the IDE to use its own Python implementation for that block of code.

A recent update to the Python sublime-syntax package bundled with ST3 has broken compatibility when a tmLanguage file attempts to defer to the sublime-syntax file.

The long-term solution would be to rewrite Sublime-Renpy to use the new sublime-syntax format. But for the time being I've been able to work around the problem by importing Sublime's own Python.sublime-syntax file (it's permissively licensed https://raw.githubusercontent.com/sublimehq/Packages/5919f45faabdfcf3932c13886f626f87070bff09/LICENSE) and removing the problematic code.

I haven't tested it thoroughly - it was only pushed 15 minutes ago - but so far everything seems to be working. It will most likely break ST2 compatibility though.

**Comment by koroshiya** [comment]
v1.2.13 is now live and installable through package manager. I've tested it on a couple machines with a variety of rpy scripts and everything appears to be working.
I'm closing this issue as 1.2.13 appears to resolve it. Please reopen if anybody finds something wrong with the new release.
